import { PageHero } from "@/components/site/PageHero";

export default function EffetMere() {
  return (
    <>
      <PageHero index="Effet Mère" title="Reality is not represented — it is generated." />
      <section className="mx-auto max-w-2xl px-5 pb-24 md:px-8">
        <div className="fm-grotesk flex flex-col gap-5 text-[15px] leading-relaxed text-fmfg/85">
          <p>
            Effet Mère is the artistic identity of Haïfa Becheikh — VJing, live performance, generative
            systems and contemporary art, in practice since 2009.
          </p>
          <p>
            The central proposition: the real is continuously generated by invisible matrices. Effet Mère
            configures conditions of appearance rather than producing fixed objects. Each performance is a
            transient state of an active system.
          </p>
        </div>
        <blockquote className="mt-10 border-l-2 border-fmaccent pl-6 text-lg italic text-fmfg/90">
          “We configure conditions of appearance, we do not produce fixed objects.”
        </blockquote>
      </section>
    </>
  );
}
